package:
    name:           omnipay-ecoin
    namespace:      Omnipay\eCoin
    headline:       Omnipay: eCoin
    title:          eCoin driver for Omnipay PHP payment library
    type:           library
    keywords:       php, ecoin, merchant
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [eCoin](http://ecoin.cc/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
