package:
    name:           php-merchant-ecoin
    namespace:      hiqdev\php\merchant\ecoin
    title:          eCoin plugin for PHP merchant library
    type:           library
    keywords:       php, ecoin, merchant
    description:    |
        [eCoin](http://ecoin.cc/) plugin for [PHP merchant library](https://github.com/hiqdev/php-merchant).

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
